### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by artemking4** [Leystryku/leysourceengineclient#11]
Sometimes the server sends you two signon packets on connectstep 4 which makes it so you cant connect further
fix - skip the second command in OOB::ReceiveQueryPacketConnection

**Comment by Leystryku** [comment]
That is not a proper fix. I will eventually make a PR to clean up the logic involving connection steps

**Comment by artemking4** [comment]
Yeah, its probably not. It did work for me though
