### ISSUE TITLE
"Server uses different class tables"

### ISSUE THREAD

**Issue by CattenCat** [Leystryku/leysourceengineclient#19]
When connecting to a Garry's Mod server I get kicked for "Server uses different class tables" even though the server I'm connecting to is running the latest version of Garry's Mod 

Logs from SourceEngineClient.exe
Sending clc_ClientInfo
Sending SignonState 3
Sending SignonState 4
Sending SignonState 5
Sending SignonState 6
Unhandled Message: 1

The server I'm connecting to logs:
3><>" disconnected (reason "Server uses different class tables")

**Comment by FlorianLeChat** [comment]
Please see: https://github.com/Leystryku/leysourceengineclient/issues/7#issuecomment-650780713
