### ISSUE TITLE
Doesn't work for me.

### ISSUE THREAD

**Issue by markusmarkusz** [Leystryku/leysourceengineclient#2]
I have compiled the program and when I run it it instantly crashes.
Visual Studio said this when I used the debugger:
`Exception thrown at 0x00000001 in leysourceengineclient.exe: 0xC0000005: Access violation executing location 0x00000001.`

Are there more informations that you/someone need to know?
What could be the reason?

**Comment by Leystryku** [comment]
It's caused by the steam loader class not being initialized properly. I've
fixed that issue in a local copy

Am 27.10.2016 16:29 schrieb "Markus" notifications@github.com:

**Comment by markusmarkusz** [comment]
Can you tell me what I have to do to make everything working for me?

**Comment by Leystryku** [comment]
Lemme push an update sec

Am 29.10.2016 7:19 nachm. schrieb "Markus" notifications@github.com:

**Comment by markusmarkusz** [comment]
Now it works. Thanks :).
