### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by pkmnmstr98** [Leystryku/leysourceengineclient#23]
Server is telling us we can connect (2x)
Sent connect packet
Received first ingame packet
Unhandled Message: 1

Changed the code to ignore the second "Server is telling us we can connect" message. After that the client showed up as connecting to the server but eventually drops once the Unhandled message gets printed.

**Comment by pkmnmstr98** [comment]
Hmmm seems to work with some servers. Doesnt work with this one specifically -->208.103.169.33:27023

**Comment by 4cuck** [comment]
know a bypass?
