### ISSUE TITLE
Disconnected: Server uses different class tables

### ISSUE THREAD

**Issue by 60percentCaffeine** [Leystryku/leysourceengineclient#3]
"Disconnected: Server uses different class tables" when trying to join any server

**Comment by GingerAdonis** [comment]
Probably due to the updates GMod received. Maybe @Leystryku can look into it.

**Comment by Leystryku** [comment]
its fixed by changing 1 number, cba to grab the new one

**Comment by GingerAdonis** [comment]
Maybe give a hint where to find the new value? Might be valuable for people looking into this project.

**Comment by 60percentCaffeine** [comment]
@Leystryku Can you tell us what number should we change? And how can we grab it?

**Comment by Leystryku** [comment]
all you have to do is change the CRC, which is in the clc_ClientInfo packet. May even be dumpable with net_showmsg clc_ClientInfo
