### ISSUE TITLE
Crashing upon starting

### ISSUE THREAD

**Issue by Xulua1499** [Leystryku/leysourceengineclient#5]
Seems to be at the following line it crashes:

`steamuser->GetAuthSessionTicket(steamkey, STEAM_KEYSIZE, &keysize);`

I'm logged into steam and it owns Garry's Mod, so I'm unsure why this isn't working. It was previously working fine until a couple weeks ago. Something updated possibly?

**Comment by Leystryku** [comment]
ye sth changed, I fixed it in my local copy doe

Xulua1499 <notifications@github.com> schrieb am Mo., 7. Mai 2018, 15:13:

**Comment by Xulua1499** [comment]
Is it a lot to change? I'm guessing something in steamworks changed

Thanks for the quick response btw

**Comment by Leystryku** [comment]
Nah it was really easy iirc

Xulua1499 <notifications@github.com> schrieb am Mo., 7. Mai 2018, 15:16:

**Comment by Xulua1499** [comment]
Any chance of seeing your fixed version? Or just that partial bit if you don't mind

**Comment by Leystryku** [comment]
cba to find it, just fiddle around and you might fix it :V

2018-05-07 15:21 GMT+02:00 Xulua1499 <notifications@github.com>:

**Comment by 60percentCaffeine** [comment]
Good support :ok_hand:

**Comment by yunusemregul** [comment]
fixed it on my fork but voice communication doesn't work for some reason
